#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xEC94D18F7F05997E (jr@jriddell.org)
#
Name     : plasma-browser-integration
Version  : 5.16.1
Release  : 19
URL      : https://download.kde.org/stable/plasma/5.16.1/plasma-browser-integration-5.16.1.tar.xz
Source0  : https://download.kde.org/stable/plasma/5.16.1/plasma-browser-integration-5.16.1.tar.xz
Source99 : https://download.kde.org/stable/plasma/5.16.1/plasma-browser-integration-5.16.1.tar.xz.sig
Summary  : Components necessary to integrate browsers into the Plasma Desktop
Group    : Development/Tools
License  : GPL-3.0
Requires: plasma-browser-integration-bin = %{version}-%{release}
Requires: plasma-browser-integration-data = %{version}-%{release}
Requires: plasma-browser-integration-lib = %{version}-%{release}
Requires: plasma-browser-integration-license = %{version}-%{release}
Requires: plasma-browser-integration-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : kactivities-dev
BuildRequires : krunner-dev
BuildRequires : plasma-framework-dev

%description
# Plasma Browser Integration
This project aims to provide better integration of web browsers with the KDE Plasma 5 desktop.

%package bin
Summary: bin components for the plasma-browser-integration package.
Group: Binaries
Requires: plasma-browser-integration-data = %{version}-%{release}
Requires: plasma-browser-integration-license = %{version}-%{release}

%description bin
bin components for the plasma-browser-integration package.


%package data
Summary: data components for the plasma-browser-integration package.
Group: Data

%description data
data components for the plasma-browser-integration package.


%package lib
Summary: lib components for the plasma-browser-integration package.
Group: Libraries
Requires: plasma-browser-integration-data = %{version}-%{release}
Requires: plasma-browser-integration-license = %{version}-%{release}

%description lib
lib components for the plasma-browser-integration package.


%package license
Summary: license components for the plasma-browser-integration package.
Group: Default

%description license
license components for the plasma-browser-integration package.


%package locales
Summary: locales components for the plasma-browser-integration package.
Group: Default

%description locales
locales components for the plasma-browser-integration package.


%prep
%setup -q -n plasma-browser-integration-5.16.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1560874484
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1560874484
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/plasma-browser-integration
cp COPYING-GPL3 %{buildroot}/usr/share/package-licenses/plasma-browser-integration/COPYING-GPL3
pushd clr-build
%make_install
popd
%find_lang plasma-browser-integration-host
%find_lang plasma-browser-integration-reminder
%find_lang plasma_runner_browsertabs

%files
%defattr(-,root,root,-)
/usr/lib/mozilla/native-messaging-hosts/org.kde.plasma.browser_integration.json

%files bin
%defattr(-,root,root,-)
/usr/bin/plasma-browser-integration-host

%files data
%defattr(-,root,root,-)
/usr/share/kservices5/plasma-runner-browsertabs.desktop

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/plugins/kf5/kded/browserintegrationreminder.so
/usr/lib64/qt5/plugins/krunner_browsertabs.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/plasma-browser-integration/COPYING-GPL3

%files locales -f plasma-browser-integration-host.lang -f plasma-browser-integration-reminder.lang -f plasma_runner_browsertabs.lang
%defattr(-,root,root,-)

