#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xEC94D18F7F05997E (jr@jriddell.org)
#
Name     : plasma-browser-integration
Version  : 5.13.5
Release  : 3
URL      : https://download.kde.org/stable/plasma/5.13.5/plasma-browser-integration-5.13.5.tar.xz
Source0  : https://download.kde.org/stable/plasma/5.13.5/plasma-browser-integration-5.13.5.tar.xz
Source99 : https://download.kde.org/stable/plasma/5.13.5/plasma-browser-integration-5.13.5.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: plasma-browser-integration-bin
Requires: plasma-browser-integration-lib
Requires: plasma-browser-integration-license
Requires: plasma-browser-integration-data
Requires: plasma-browser-integration-locales
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : kactivities-dev
BuildRequires : krunner-dev
BuildRequires : plasma-framework-dev

%description
No detailed description available

%package bin
Summary: bin components for the plasma-browser-integration package.
Group: Binaries
Requires: plasma-browser-integration-data
Requires: plasma-browser-integration-license

%description bin
bin components for the plasma-browser-integration package.


%package data
Summary: data components for the plasma-browser-integration package.
Group: Data

%description data
data components for the plasma-browser-integration package.


%package lib
Summary: lib components for the plasma-browser-integration package.
Group: Libraries
Requires: plasma-browser-integration-data
Requires: plasma-browser-integration-license

%description lib
lib components for the plasma-browser-integration package.


%package license
Summary: license components for the plasma-browser-integration package.
Group: Default

%description license
license components for the plasma-browser-integration package.


%package locales
Summary: locales components for the plasma-browser-integration package.
Group: Default

%description locales
locales components for the plasma-browser-integration package.


%prep
%setup -q -n plasma-browser-integration-5.13.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536089254
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1536089254
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/plasma-browser-integration
cp COPYING-GPL3 %{buildroot}/usr/share/doc/plasma-browser-integration/COPYING-GPL3
pushd clr-build
%make_install
popd
%find_lang plasma_runner_browsertabs

%files
%defattr(-,root,root,-)
/usr/lib/mozilla/native-messaging-hosts/org.kde.plasma.browser_integration.json

%files bin
%defattr(-,root,root,-)
/usr/bin/plasma-browser-integration-host

%files data
%defattr(-,root,root,-)
/usr/share/kservices5/plasma-runner-browsertabs.desktop

%files lib
%defattr(-,root,root,-)
/usr/lib64/qt5/plugins/kf5/kded/browserintegrationreminder.so
/usr/lib64/qt5/plugins/krunner_browsertabs.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/plasma-browser-integration/COPYING-GPL3

%files locales -f plasma_runner_browsertabs.lang
%defattr(-,root,root,-)

